### ISSUE TITLE
define the project labels.

### ISSUE THREAD

**Issue by tjkemper** [revaturelabs/boilerplate-project#1]
# define the project labels

##### for-new-contributors
* `for-new-contributors`
##### priority
* `priority/critical`
* `priority/high`
* `priority/normal`
* `priority/low`
##### kind
* `kind/bug`
* `kind/feature`
* `kind/documentation`
* `kind/question`

### Borrow from open source
* [Kubernetes](https://github.com/kubernetes/kubernetes/labels)
* [Docker](https://github.com/docker/docker/labels)

### Other links
* [Quora](https://www.quora.com/What-is-the-best-way-to-name-GitHub-issue-labels)

**Comment by ghost** [comment]
@tjkemper i would think that the labels should be implemented for all contributors, not just new peeps.

**Comment by ghost** [comment]
good meeting today... let's get it done!

**Comment by tjkemper** [comment]
Checkout the labels.

**Comment by ghost** [comment]
the labels need more colors.

**Comment by RevatureSteve** [comment]
I think the type/ should all share the same color to help eliminate the chance of having multiples

**Comment by tjkemper** [comment]
Labels are created.  Please add them to your respective repos.

Note: copy the hex for each color
